# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, max_length=255),
        ),
    ]
